### ISSUE TITLE
Android: "received" event is not triggered

### ISSUE THREAD

**Issue by swey** [cleverpush/cleverpush-react-native-sdk#15]
On Android the "received" Event won't be triggered.

After looking into the Android implementation it seems like there is only an implementation for the SubscribedListener and OpenedListener: https://github.com/cleverpush/cleverpush-react-native-sdk/blob/af8f6c73ef872abe7ca94611583892078ee7ad4d/android/src/main/java/com/cleverpush/reactnative/RNCleverPush.java#L114-L119

**Comment by gbhrdt** [comment]
Hi @swey thanks for reporting, we are currently working on this and will get back ASAP.

**Comment by gbhrdt** [comment]
Released in version 1.7.5
