### ISSUE TITLE
[Android] "One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified" when targetSdkVersion is 34

### ISSUE THREAD

**Issue by cuelebra** [cleverpush/cleverpush-react-native-sdk#9]
After upgrading RN to 0.74 and setting targetSdkVersion to 34, the app throws an error:

> com.brand.app:
> One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

the stacktrace points to RNCleverPush.java file:
```
    private void registerNotificationsOpenedNotification() {
        IntentFilter intentFilter = new IntentFilter(NOTIFICATION_OPENED_INTENT_FILTER);
        mReactContext.registerReceiver(new BroadcastReceiver() {
            @Override
            public void onReceive(Context context, Intent intent) {
                notifyNotificationOpened(intent.getExtras());
            }
        }, intentFilter);
    }
```
When app targets Android 14 and runs on Androird 14, calling registerReceiver without a third required parameter throws an exception now. RN fixed it this way:
https://github.com/facebook/react-native/commit/177d97d8ea962bdd4dad8fcf0efb04a307f25000

**Comment by gbhrdt** [comment]
Thanks for reporting! Fixed with #11 and released with version 1.7.2
